### ISSUE TITLE
Re-enable site archiving in archive.org?

### ISSUE THREAD

**Issue by mariomadproductions** [byuu/byuu.org#4]
Currently its disabled. 
![image](https://user-images.githubusercontent.com/9919020/89100835-5fbd2880-d3f2-11ea-97a7-81722c5390f3.png)

**Comment by Screwtapello** [comment]
byuu felt very strongly about excluding the historical content of the website from archive.org, and archiving was one of the things that forced him to retire in the first place.

It'd probably be fine to archive the *current* content of byuu.org, but it's already archived here on GitHub, and I expect that's good enough. I don't feel strongly enough about archiving to figure out how to re-enable it - I've got other stuff to do.

Thanks for the idea, though.

**Comment by mariomadproductions** [comment]
Yeah I understand he might not want some old blogposts etc archived. I'm really just interested in the current technical info (e.g. the SNES cart database). But yeah, this being a git does make archiving reasonably straightforward.
