### ISSUE TITLE
Set up subdomain preservation.byuu.org to redirect to byuu.org/preservation.

### ISSUE THREAD

**Issue by jchv** [byuu/byuu.org#8]
This is just a nice idea to at least make links to somewhere somewhat useful, since otherwise it is confusing. It could probably be accomplished with a separate GH pages link with a typical HTML redirect, or maybe the registar byuu.org is controlled under has a redirect feature that can automate it instead.

**Comment by Screwtapello** [comment]
There's now a GitHub pages repo at https://github.com/byuu/preservation.byuu.org which contains only a redirect to https://byuu.org/preservation/

It would be nice to have a browsable website like what used to be at preservation.byuu.org, but now we have a Pages repo we can set up a site generator when we get around to it, and maybe make the redirection go the other way.

**Comment by Screwtapello** [comment]
I guess this is done, we can track other parts of making a preservation website in that repo.
